apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-service
          image: wjswoghks/main-service:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1024Mi"
              cpu: "750m"
            limits:
              memory: "2048Mi"
              cpu: "1500m"