spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/price_tracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 6585qwer^
  kafka:
    bootstrap-servers:
      - 54.172.163.13:9092
      - 18.233.82.55:9092
      - 100.24.176.111:9092
    consumer:
      group-id: price-storage-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest
  data:
    mongodb:
      uri: mongodb://localhost:27017/pricewatcher

coolsms:
  api:
    key: NCSNE0EKVTZAUCCY
    secret: V1SHVAWC0NI4DN9YE1LP3FTN12WSBHG

ebay:
  client-id: "jeonjaeh-PriceAle-PRD-0e1c6dfdd-487315a8"
  client-secret: "PRD-e1c6dfdd6127-1f20-476e-a24b-8ce9"


server:
  port: 8082
